### ISSUE TITLE
Verificar se o arquivo de template foi editado

### ISSUE THREAD

**Issue by ghost** [renatolouro/Simplate#1]
Ao alterar o arquivo de template HTML não deveria verificar se existiu alguma alteração desde a geração do último arquivo?
Deve ter alguma forma de gerar isso de forma simples, talvez adicionando um comentário dentro do destino e verificando via ER.

Para que cada alteração não seja necessário excluir o arquivo de cache para que seja novamente gerado.

**Comment by renatolouro** [comment]
Olá Michel.
Se entendi bem o que você pede, ele já faz isso. Veja a função record() de CSimplate. Ele só gera o cache sobre determinadas condições ver linha 150 de CSimplate 00.001 Alfa.
A principal condição é se o cache é mais antigo do que o template. Neste caso o cache deve ser regerado, pois se entende como desatualizado.
A outra condição para regerar o cache é se a variável de configuração SPL_FORCE == true. Neste caso o cache é sempre regerado. É útil principalmente para desenvolvimento do próprio Simplate quando modificamos o gerador e queremos ver o cache resultante. Perceba que neste caso não estamos alterando o template mas, mesmo assim queremos ver como o cache está sendo construído.

Em teoria na linha 63 - if (!defined('SPL_FORCE')) define('SPL_FORCE', false); - deveria seta-lo como falso por padrão.
Ou seja, por padrão o simplate só deveria regerar o cache caso o template seja atualizado.

Não está se comportando assim, aí?

**Comment by renatolouro** [comment]
Olá Michel,
Acho que matei a charada.
Como disse por mensagens privadas a chave para entender o porque não funciona no seu ambiente está na linha: 150 onde ocorre o IF que verifica se o cache deve ou não deve ser reescrito.

Também comentei que provavelmente a questão estaria relacionada com diferenças entre linux/windows já que nossas máquinas e as dos nossos clientes são 100% linux.

Pois bem, existe um bug documentado no PHP em relação as funções filemtime/fileatime/filectime no ambiente windows. E nós utilizamos a função filemtime para verificar se o cache é mais antigo do que o template

Veja em https://bugs.php.net/bug.php?id=40568

Neste comentário http://www.php.net/manual/en/function.filemtime.php#100692 o usuário cria a função GetCorrectMTime, como uma alternativa a função nativa filemtime driblando tal bug.
Então acho que a 1a ação é testarmos esta função fornecida neste comentário para ver se o bug é solucionado.

**Comment by ghost** [comment]
Resolvido colocando o SPL_FORCE como true antes de incluir, este foi meu erro.

Erro meu, foi mal!

Geralmente instancio essas coisas e verifico na criação dos objetos e não no próprio arquivo.
